### ISSUE TITLE
title missing on feed

### ISSUE THREAD

**Issue by rinzes** [RebelCodeBase/sopel-rss#12]
Not sure whats causing this on this feed: http://www.cnbc.com/id/100003114/device/rss/rss.html

Sometimes the title is mssing.. example

<Sopel> [CNBC] → http://tinyurl.com/hamzwv9
<Sopel> [CNBC] → http://tinyurl.com/hpg9z4z

**Comment by RebelCodeBase** [comment]
I cannot reproduce this bug, it seems to work all right. Do you have any additional info?

**Comment by rinzes** [comment]
No I sure don't other then it appears to be not consistent. It also happen on occasion in a couple others. I looked in the direct feed and the titles are there.

**Comment by RebelCodeBase** [comment]
I've released another version. This is hopefully the last change in syntax. The new syntax in the config file is: 
feeds =  #channel1;feed1;http://www.site1.com/feed;f=fl+fty;t=f|%03%16[{}]%20;t=t|%16[{}]%20,#channel2;feed2;...
Here f=XX+YY is the new syntax for formats (what will be cached + what will be printed) and t=X|A{}B is the new syntax for templates (how will it be printed). Both can be configured for each feed so you can for example color code your feeds.

Still I cannot reproduce your problem. Could you please confirm that it still exists in v0.3.0?

**Comment by rinzes** [comment]
I'm posting this here unless you want me to open a new issue 

I'm starting with a clean cfg file.. No feeds or formats/templates.

When I do .rss config formats I get fl+ftl as expected
then I do .rss config formats fl+fty
then I do .rss config formats I get f=f;f=l;f=+;f=f;f=t;f=l;f=fl+ftl 
not what I was expecting ie fl+fty fl+ftl
I checked the cfg file and formats = was not there

**Comment by RebelCodeBase** [comment]
I can reproduce you input. There are two problems here:

1) Your input should have been: 

```
.rss config formats f=fl+fty
```

Then the output of .rss config formats is:

```
f=fl+fty;f=fl+ftl
```

And in the config file:

```
formats = f=fl+fty
```

This is expected. The interactive format gives your custom default format and the global default format. The config file has only your custom format. This is because the global default format is defined in the .py file as a global fallback while the custom default format is set in the config file.

2) Obviously, your input should have been rejected with a meaningful error message. I will fix that.

**Comment by RebelCodeBase** [comment]
And yes: please open a separate issue for each problem in the future.

**Comment by RebelCodeBase** [comment]
I've fixed the invalid input problem and I've made yet another release (v0.3.1)
Back to this issue: I cannot reproduce your problem. Could you please confirm that it still exists in v0.3.1?

**Comment by rinzes** [comment]
Yeap

[04:35] <Sopel> [AP-Business] Libyan troops recapture key oil terminals from militia → http://tinyurl.com/5tovp4s
[05:26] <Sopel> [SPY] Why It's Important To Have Gold In Your Portfolio → http://tinyurl.com/jxkxvzj
[05:31] <Sopel> [SPY] Why It's Important To Have Gold In Your Portfolio → http://tinyurl.com/h83h22q
[05:41] <Sopel> [SPY] → http://tinyurl.com/zotgj3u
[05:45] <Sopel> [SPY] → http://tinyurl.com/gsqrorn
[05:50] <Sopel> [AP-Business] Conservative push to impeach IRS chief; effort won't succeed → http://tinyurl.com/j2e6tzj
[05:54] <Sopel> [AP-Business] The Onion ramps up speed of satire in Campaign 2016 → http://tinyurl.com/j264l9e
[05:58] <Sopel> [CNBC] Bank of Japan looks to clarify policy confusion but markets still bewildered → http://tinyurl.com/jmv5eb5

**Comment by RebelCodeBase** [comment]
Could you please post .rss list SPY? I need to know which title causes this error, i.e. the source code of the feed item.

**Comment by rinzes** [comment]
SPY http://markets.financialcontent.com/stocks/action/rssfeed?Symbol=SPY t=f|[%03%13{}%20]

**Comment by rinzes** [comment]
also this one:

IBD_Economy http://www.investors.com/rss.axd?path=EconomyRSS.xml t=f|[%03%10{}%20]

**Comment by RebelCodeBase** [comment]
Now this was a real bug! The problem was that I first inserted the field value and then parsed the template. Then a % sign for example in a title was interpreted as a formatting escape character. Now I first interpret the template and afterwards insert the field value. Please reopen if the error occurs again.
